# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_header_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercontrolpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_header_control_headercontrolpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]